
package com.rpc.ws.service.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MessengerServiceImplService", targetNamespace = "http://impl.service.ws.rpc.com/", wsdlLocation = "http://localhost:8080/ws/message?wsdl")
public class MessengerServiceImplService
    extends Service
{

    private final static URL MESSENGERSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MESSENGERSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName MESSENGERSERVICEIMPLSERVICE_QNAME = new QName("http://impl.service.ws.rpc.com/", "MessengerServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws/message?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MESSENGERSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        MESSENGERSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public MessengerServiceImplService() {
        super(__getWsdlLocation(), MESSENGERSERVICEIMPLSERVICE_QNAME);
    }

    public MessengerServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MESSENGERSERVICEIMPLSERVICE_QNAME, features);
    }

    public MessengerServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, MESSENGERSERVICEIMPLSERVICE_QNAME);
    }

    public MessengerServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MESSENGERSERVICEIMPLSERVICE_QNAME, features);
    }

    public MessengerServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MessengerServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MessengerService
     */
    @WebEndpoint(name = "MessengerServiceImplPort")
    public MessengerService getMessengerServiceImplPort() {
        return super.getPort(new QName("http://impl.service.ws.rpc.com/", "MessengerServiceImplPort"), MessengerService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MessengerService
     */
    @WebEndpoint(name = "MessengerServiceImplPort")
    public MessengerService getMessengerServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.ws.rpc.com/", "MessengerServiceImplPort"), MessengerService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MESSENGERSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw MESSENGERSERVICEIMPLSERVICE_EXCEPTION;
        }
        return MESSENGERSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
